#ifndef LIBUVC_CONFIG_H
#define LIBUVC_CONFIG_H

#define LIBUVC_VERSION_MAJOR 0
#define LIBUVC_VERSION_MINOR 0
#define LIBUVC_VERSION_PATCH 7
#define LIBUVC_VERSION_STR "0.0.7-esp"
#define LIBUVC_VERSION_INT ((LIBUVC_VERSION_MAJOR << 16) | (LIBUVC_VERSION_MINOR << 8) | LIBUVC_VERSION_PATCH)
#define LIBUVC_VERSION_GTE(major, minor, patch) \
  (LIBUVC_VERSION_INT >= (((major) << 16) | ((minor) << 8) | (patch)))

#ifndef LIBUVC_NUM_TRANSFER_BUFS
#define LIBUVC_NUM_TRANSFER_BUFS 4
#endif

#endif
