#pragma once

#include <Arduino.h>

#define P1_EMBED_FIRMWARE_NAME "p1_embed"
#define P1_EMBED_FIRMWARE_VERSION "0.1.139"
#define P1_EMBED_PROTOCOL_VERSION "0.1"
#define P1_EMBED_WRENCH_API_VERSION "0.1"
#define P1_EMBED_WRENCH_UPSTREAM_REPO "https://github.com/jingoro2112/wrench"
#define P1_EMBED_WRENCH_UPSTREAM_COMMIT "c84d57ee7df6032e90a9cfee2ba24033045b81ec"
#define P1_EMBED_BUILD_CHANNEL "webrtc-lab"

#define P1_EMBED_SERIAL_BAUD 115200
#define P1_EMBED_LINE_MAX 12288
#define P1_EMBED_MAX_SCRIPT_BYTES 16384
#define P1_EMBED_WRENCH_ENABLED 1
#define P1_EMBED_WRENCH_AUTORUN_ENABLED 1
#define P1_EMBED_STATUS_INTERVAL_MS 10000
#define P1_EMBED_MEMORY_PROFILE_ENABLED 1
#define P1_EMBED_MEMORY_PROFILE_SAMPLES 48
#define P1_EMBED_MEMORY_PROFILE_DEFAULT_LIMIT 16
#define P1_EMBED_DEFAULT_LED_PIN 2
#define P1_EMBED_SCRIPT_VERIFY_MS 10000
#define P1_EMBED_BOOT_AUTORUN_WIFI_WAIT_MS 30000
#define P1_EMBED_BOOT_AUTORUN_WEBRTC_SETTLE_MS 7000
#define P1_EMBED_MAX_WIFI_NETWORKS 5
#define P1_EMBED_WRENCH_TASK_STACK 5120
#define P1_EMBED_WRENCH_COMPILE_TASK_STACK 24576
#define P1_EMBED_WRENCH_COMPILE_MIN_FREE_HEAP 65536
#define P1_EMBED_WRENCH_COMPILE_MIN_MAX_ALLOC 24576
#define P1_EMBED_WRENCH_COMPILE_HEAP_SETTLE_MS 1500
#define P1_EMBED_WRENCH_LARGE_SCRIPT_BYTES 4096
#define P1_EMBED_WRENCH_LARGE_COMPILE_MIN_FREE_HEAP 81920
#define P1_EMBED_WRENCH_LARGE_COMPILE_MIN_MAX_ALLOC 40960
#define P1_EMBED_WRENCH_WEBRTC_LARGE_SCRIPT_BYTES 4096
#define P1_EMBED_WRENCH_WEBRTC_COMPILE_MIN_FREE_HEAP 98304
#define P1_EMBED_WRENCH_WEBRTC_COMPILE_MIN_MAX_ALLOC 40960
#define P1_EMBED_WRENCH_TASK_DELAY_MS 1
#define P1_EMBED_WRENCH_LOCK_STATUS_TIMEOUT_MS 5
#define P1_EMBED_WRENCH_LOOP_WARN_MS 1000
#define P1_EMBED_WRENCH_LOOP_HUNG_MS 10000
#define P1_EMBED_WRENCH_ERROR_LOOP_LIMIT 5
#define P1_EMBED_SCRIPT_ERROR_EMIT_REPEAT_MS 1000
#define P1_EMBED_WRENCH_INSTRUCTIONS_PER_SLICE 1000
#define P1_EMBED_WRENCH_GC_HINT_BYTES 512
#define P1_EMBED_WRENCH_TRANSITION_TIMEOUT_MS 5000
#define P1_EMBED_PROTOCOL_QUEUE_DEPTH 8
#define P1_EMBED_PROTOCOL_QUEUE_LINE_MAX 384
#define P1_EMBED_DEBUG_FLUSH_BUDGET 4
#define P1_EMBED_DEBUG_DEFAULT_LEVEL 2
#define P1_EMBED_WRENCH_INBOX_DEPTH 8
#define P1_EMBED_WRENCH_INBOX_CHANNEL_MAX 32
#define P1_EMBED_WRENCH_INBOX_MESSAGE_MAX 256
#define P1_EMBED_UI_EVENT_DEPTH 8
#define P1_EMBED_UI_STATE_MAX 24
#define P1_EMBED_UI_ID_MAX 32
#define P1_EMBED_UI_TYPE_MAX 12
#define P1_EMBED_UI_TEXT_MAX 48
#define P1_EMBED_UI_VALUE_MIN_MS 250
#define P1_EMBED_UI_PUSH_MIN_MS 250
#define P1_EMBED_UI_VALUE_FLUSH_BUDGET 2
#define P1_EMBED_UI_OUT_DEPTH 32
#define P1_EMBED_UI_OUT_FLUSH_BUDGET 4
#define P1_EMBED_PWM_MAX_PINS 12
#define P1_EMBED_MAX_BYTECODE_BYTES 16384
#define P1_EMBED_WS_ENABLED 0
#define P1_EMBED_WS_PORT 81
#define P1_EMBED_MQTT_ENABLED 1
#define P1_EMBED_MQTT_HOST "public.cloud.shiftr.io"
#define P1_EMBED_MQTT_PORT 1883
#define P1_EMBED_MQTT_USER "public"
#define P1_EMBED_MQTT_PASS "public"
#define P1_EMBED_MQTT_ROOT ""
#define P1_EMBED_MQTT_BUFFER_BYTES 8192
#define P1_EMBED_MQTT_SCRIPT_CHUNK_BYTES 3000
#define P1_EMBED_MQTT_EVENT_BATCH_BYTES 3000
#define P1_EMBED_MQTT_EVENT_BATCH_FRAMES 8
#define P1_EMBED_MQTT_RECONNECT_MS 5000
#define P1_EMBED_MQTT_KEEPALIVE_SECONDS 30
#define P1_EMBED_MQTT_TIMEOUT_MS 3000
#define P1_EMBED_MQTT_MAX_USERS 4
#define P1_EMBED_MQTT_SESSION_IDLE_MS 60000
#define P1_EMBED_WEBRTC_ENABLED 0
#define P1_EMBED_WEBRTC_SIGNALING_PEERJS 0
#define P1_EMBED_WEBRTC_SIGNALING_MQTT 1
#define P1_EMBED_WEBRTC_PEERJS_HOST "0.peerjs.com"
#define P1_EMBED_WEBRTC_PEERJS_PORT 443
#define P1_EMBED_WEBRTC_PEERJS_PATH "/"
#define P1_EMBED_WEBRTC_PEERJS_KEY "peerjs"
#define P1_EMBED_WEBRTC_PEERJS_SECURE 1
#define P1_EMBED_WEBRTC_AUTO_SUFFIX_ID 0
#define P1_EMBED_WEBRTC_PEER_TASK_STACK 12288
#define P1_EMBED_WEBRTC_SIGNAL_TASK_STACK 4096
#define P1_EMBED_WEBRTC_SEND_QUEUE_DEPTH 16
#define P1_EMBED_WEBRTC_SEND_MAX_BYTES P1_EMBED_LINE_MAX
#define P1_EMBED_MSGPACK_MAX_FRAME_BYTES 2048
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_MIN_FREE_HEAP 45000
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_MIN_MAX_ALLOC 24576
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_FORCE_AFTER 5
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_LOG_MS 5000
#define P1_EMBED_WEBRTC_MAX_CONNECT_FAILURES 0
#define P1_EMBED_WEBRTC_RECONNECT_INTERVAL_MS 5000
#define P1_EMBED_WEBRTC_ID_TAKEN_RETRY_MS 30000
#define P1_EMBED_WEBRTC_ANSWER_RECONNECT_MS 5000
#define P1_EMBED_WEBRTC_PAUSE_SIGNALING_FOR_ANSWER 0
#define P1_EMBED_WEBRTC_ANSWER_SIGNAL_WAIT_MS 3000
#define P1_EMBED_WEBRTC_PARK_SIGNALING_WHEN_CONNECTED 1
#define P1_EMBED_WEBRTC_MQTT_HOST "public.cloud.shiftr.io"
#define P1_EMBED_WEBRTC_MQTT_PORT 1883
#define P1_EMBED_WEBRTC_MQTT_USER "public"
#define P1_EMBED_WEBRTC_MQTT_PASS "public"
#define P1_EMBED_WEBRTC_MQTT_ROOT "p1e-webrtc-v1"
#define P1_EMBED_WEBRTC_MQTT_BUFFER_BYTES 8192
#define P1_EMBED_FASTLED_MAX_LEDS 512
#define P1_EMBED_MAX_LED_STRIPS 4
#define P1_EMBED_UART_READ_STRING_MAX 256
#define P1_EMBED_HTTP_MAX_RESPONSE_BYTES 4096
#define P1_EMBED_HTTP_DEFAULT_TIMEOUT_MS 5000
#define P1_EMBED_JSON_ARG_MAX_BYTES 4096
#define P1_EMBED_JSON_PATH_MAX_PARTS 8

#define P1_EMBED_SCRIPT_RUN_NONE 0
#define P1_EMBED_SCRIPT_RUN_PENDING_NEW 1
#define P1_EMBED_SCRIPT_RUN_PENDING_TRIED 2
#define P1_EMBED_SCRIPT_RUN_OK 3
#define P1_EMBED_SCRIPT_RUN_STOPPED 4

static const char* P1_EMBED_CAPABILITIES[] = {
  "transport.serial.jsonl",
#if P1_EMBED_WS_ENABLED
  "transport.websocket.json",
  "discovery.mdns",
#endif
#if P1_EMBED_WEBRTC_ENABLED
  "transport.webrtc.msgpack",
  "protocol.msgpack.v0_2",
#if P1_EMBED_WEBRTC_SIGNALING_PEERJS
  "transport.webrtc.signaling.peerjs",
#endif
#if P1_EMBED_WEBRTC_SIGNALING_MQTT
  "transport.webrtc.signaling.mqtt",
#endif
#endif
#if P1_EMBED_MQTT_ENABLED
  "transport.mqtt.msgpack",
  "protocol.msgpack.v0_2",
#endif
  "protocol.v0_1",
  "memory.profile",
#if P1_EMBED_WRENCH_ENABLED
  "wrench.compile",
  "wrench.setup_loop",
  "wrench.task",
  "wrench.time_slices",
  "wrench.runtime_mutex",
  "wrench.watchdog.status",
  "debug.event_bus",
  "debug.level_filter",
  "wrench.bindings.core",
  "config.fs.json",
  "config.identity.mac",
  "wifi.station",
  "wifi.station.fallbacks",
  "script.storage.littlefs",
  "script.autorun.safe_latch",
  "wrench.bindings.protocol_services",
  "wrench.bindings.http_fetch",
  "wrench.bindings.json_helpers",
  "wrench.bindings.ui_guino",
  "wrench.inbox.protocol_input",
  "wrench.bindings.esp_basic",
  "wrench.bindings.i2c_basic",
  "wrench.bindings.secondary_uart",
  "wrench.bindings.pwm_servo_fan",
  "wrench.bindings.led_ws2812b",
  "wrench.bindings.led_hsv",
#endif
  "led.manager.multistrip",
  "script.error.last"
};

static const int P1_EMBED_CAPABILITY_COUNT =
  sizeof(P1_EMBED_CAPABILITIES) / sizeof(P1_EMBED_CAPABILITIES[0]);
