#pragma once

#include <Arduino.h>

#define XOBIT_PRODUCT_NAME "XOBIT"
#define XOBIT_FIRMWARE_NAME "xobit"
#define XOBIT_DEVICE_ID_PREFIX "xobit"
#define XOBIT_LEGACY_DEVICE_ID_PREFIX "p1-embed"
#define XOBIT_MQTT_TOPIC_PREFIX "xobit"
#define XOBIT_MQTT_CLIENT_PREFIX "xobit"
#define XOBIT_MQTT_AUTH_DOMAIN "XOBIT-MQTT-AUTH-v1"
#define XOBIT_MQTT_SECURE_DOMAIN "XOBIT-MQTT-SECURE-v1"
#define XOBIT_WEBRTC_MQTT_ROOT "xobit-webrtc-v1"

#define P1_EMBED_FIRMWARE_NAME XOBIT_FIRMWARE_NAME
#define P1_EMBED_FIRMWARE_VERSION "0.1.186"
#define P1_EMBED_PROTOCOL_VERSION "0.1"
#define P1_EMBED_WRENCH_API_VERSION "0.1"
#define P1_EMBED_WRENCH_UPSTREAM_REPO "https://github.com/jingoro2112/wrench"
#define P1_EMBED_WRENCH_UPSTREAM_COMMIT "c84d57ee7df6032e90a9cfee2ba24033045b81ec"
#define P1_EMBED_BUILD_CHANNEL "webrtc-lab"

#define P1_EMBED_SERIAL_BAUD 115200
#define P1_EMBED_LINE_MAX 12288
#define P1_EMBED_SERIAL_JSON_LINE_MAX 2048
#define P1_EMBED_MAX_SCRIPT_BYTES 16384
#ifndef P1_EMBED_WRENCH_ENABLED
#define P1_EMBED_WRENCH_ENABLED 1
#endif
#ifndef P1_EMBED_WRENCH_AUTORUN_ENABLED
#define P1_EMBED_WRENCH_AUTORUN_ENABLED 1
#endif
#define P1_EMBED_STATUS_INTERVAL_MS 10000
#define P1_EMBED_MEMORY_PROFILE_ENABLED 0
#define P1_EMBED_MEMORY_PROFILE_SAMPLES 16
#define P1_EMBED_MEMORY_PROFILE_DEFAULT_LIMIT 8
#define P1_EMBED_DEFAULT_LED_PIN 2
#define P1_EMBED_SCRIPT_VERIFY_MS 10000
#define P1_EMBED_BOOT_AUTORUN_WIFI_WAIT_MS 30000
#define P1_EMBED_BOOT_AUTORUN_WEBRTC_SETTLE_MS 7000
#define P1_EMBED_MAX_WIFI_NETWORKS 5
#define P1_EMBED_WIFI_RSSI_INTERVAL_MS 5000
#define P1_EMBED_WRENCH_TASK_STACK 5120
#define P1_EMBED_WRENCH_TASK_CORE 1
#define P1_EMBED_WRENCH_COMPILE_TASK_CORE 1
#define P1_EMBED_WRENCH_VM_STACK 1024
#define P1_EMBED_WRENCH_COMPILE_TASK_STACK 20480
#define P1_EMBED_WRENCH_COMPILE_SOURCE_RETAIN_MIN 8192
#define P1_EMBED_WRENCH_COMPILE_SOURCE_RETAIN_MAX 24576
#define P1_EMBED_WRENCH_COMPILE_SOURCE_SHRINK_IDLE_MS 30000
#define P1_EMBED_WRENCH_COMPILE_MIN_FREE_HEAP 65536
#define P1_EMBED_WRENCH_COMPILE_MIN_MAX_ALLOC 24576
#define P1_EMBED_WRENCH_COMPILE_HEAP_SETTLE_MS 1500
#define P1_EMBED_WRENCH_LARGE_SCRIPT_BYTES 4096
#define P1_EMBED_WRENCH_LARGE_COMPILE_MIN_FREE_HEAP 81920
#define P1_EMBED_WRENCH_LARGE_COMPILE_MIN_MAX_ALLOC 32768
#define P1_EMBED_WRENCH_WEBRTC_LARGE_SCRIPT_BYTES 4096
#define P1_EMBED_WRENCH_WEBRTC_COMPILE_MIN_FREE_HEAP 98304
#define P1_EMBED_WRENCH_WEBRTC_COMPILE_MIN_MAX_ALLOC 40960
#define P1_EMBED_WRENCH_TASK_DELAY_MS 1
#define P1_EMBED_WRENCH_HIGH_FPS_THRESHOLD 300.0f
#define P1_EMBED_WRENCH_HIGH_FPS_EXTRA_DELAY_MS 1
#define P1_EMBED_WRENCH_LOCK_STATUS_TIMEOUT_MS 5
#define P1_EMBED_WRENCH_LOOP_WARN_MS 1000
#define P1_EMBED_WRENCH_LOOP_HUNG_MS 10000
#define P1_EMBED_WRENCH_ERROR_LOOP_LIMIT 5
#define P1_EMBED_SCRIPT_ERROR_EMIT_REPEAT_MS 1000
#define P1_EMBED_SCRIPT_ERROR_PHASE_MAX 16
#define P1_EMBED_SCRIPT_ERROR_CODE_MAX 48
#define P1_EMBED_SCRIPT_ERROR_MESSAGE_MAX 192
#define P1_EMBED_SCRIPT_ERROR_DETAILS_MAX 256
#define P1_EMBED_WRENCH_INSTRUCTIONS_PER_SLICE 1000
#define P1_EMBED_WRENCH_GC_HINT_BYTES 512
#define P1_EMBED_WRENCH_TRANSITION_TIMEOUT_MS 5000
#define P1_EMBED_PROTOCOL_QUEUE_DEPTH 8
#define P1_EMBED_PROTOCOL_QUEUE_LINE_MAX 384
#define P1_EMBED_DEBUG_FLUSH_BUDGET 4
#define P1_EMBED_DEBUG_DEFAULT_LEVEL 2
#define P1_EMBED_WRENCH_INBOX_DEPTH 8
#define P1_EMBED_WRENCH_INBOX_CHANNEL_MAX 32
#define P1_EMBED_WRENCH_INBOX_MESSAGE_MAX 256
#define P1_EMBED_UI_EVENT_DEPTH 8
#define P1_EMBED_UI_STATE_MAX 16
#define P1_EMBED_UI_ID_MAX 32
#define P1_EMBED_UI_TYPE_MAX 12
#define P1_EMBED_UI_TEXT_MAX 48
#define P1_EMBED_UI_VALUE_MIN_MS 250
#define P1_EMBED_UI_PUSH_MIN_MS 250
#define P1_EMBED_UI_VALUE_FLUSH_BUDGET 2
#define P1_EMBED_UI_OUT_DEPTH 16
#define P1_EMBED_UI_OUT_FLUSH_BUDGET 4
#define P1_EMBED_PWM_MAX_PINS 12
#define P1_EMBED_MAX_BYTECODE_BYTES 16384
#define P1_EMBED_WS_ENABLED 0
#define P1_EMBED_WS_PORT 81
#ifndef P1_EMBED_MQTT_ENABLED
#define P1_EMBED_MQTT_ENABLED 1
#endif
#define P1_EMBED_MQTT_HOST "public.cloud.shiftr.io"
#define P1_EMBED_MQTT_PORT 1883
#define P1_EMBED_MQTT_USER "public"
#define P1_EMBED_MQTT_PASS "public"
#define P1_EMBED_MQTT_ROOT ""
#define P1_EMBED_MQTT_BUFFER_BYTES 4096
#define P1_EMBED_MQTT_SCRIPT_CHUNK_BYTES 1024
#define P1_EMBED_MQTT_EVENT_BATCH_BYTES 3000
#define P1_EMBED_MQTT_EVENT_BATCH_FRAMES 8
#define P1_EMBED_MQTT_OUT_QUEUE_DEPTH 8
#define P1_EMBED_MQTT_OUT_QUEUE_BYTES 768
#define P1_EMBED_MQTT_RECONNECT_MS 5000
#define P1_EMBED_MQTT_KEEPALIVE_SECONDS 30
#define P1_EMBED_MQTT_TIMEOUT_MS 3000
#define P1_EMBED_MQTT_MAX_USERS 4
#define P1_EMBED_MQTT_SESSION_IDLE_MS 60000
#define P1_EMBED_WEBRTC_ENABLED 0
#define P1_EMBED_WEBRTC_SIGNALING_PEERJS 0
#define P1_EMBED_WEBRTC_SIGNALING_MQTT 1
#define P1_EMBED_WEBRTC_PEERJS_HOST "0.peerjs.com"
#define P1_EMBED_WEBRTC_PEERJS_PORT 443
#define P1_EMBED_WEBRTC_PEERJS_PATH "/"
#define P1_EMBED_WEBRTC_PEERJS_KEY "peerjs"
#define P1_EMBED_WEBRTC_PEERJS_SECURE 1
#define P1_EMBED_WEBRTC_AUTO_SUFFIX_ID 0
#define P1_EMBED_WEBRTC_PEER_TASK_STACK 12288
#define P1_EMBED_WEBRTC_SIGNAL_TASK_STACK 4096
#define P1_EMBED_WEBRTC_SEND_QUEUE_DEPTH 16
#define P1_EMBED_WEBRTC_SEND_MAX_BYTES P1_EMBED_LINE_MAX
#define P1_EMBED_MSGPACK_MAX_FRAME_BYTES 2048
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_MIN_FREE_HEAP 45000
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_MIN_MAX_ALLOC 24576
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_FORCE_AFTER 5
#define P1_EMBED_WEBRTC_SCRIPT_RESUME_LOG_MS 5000
#define P1_EMBED_WEBRTC_MAX_CONNECT_FAILURES 0
#define P1_EMBED_WEBRTC_RECONNECT_INTERVAL_MS 5000
#define P1_EMBED_WEBRTC_ID_TAKEN_RETRY_MS 30000
#define P1_EMBED_WEBRTC_ANSWER_RECONNECT_MS 5000
#define P1_EMBED_WEBRTC_PAUSE_SIGNALING_FOR_ANSWER 0
#define P1_EMBED_WEBRTC_ANSWER_SIGNAL_WAIT_MS 3000
#define P1_EMBED_WEBRTC_PARK_SIGNALING_WHEN_CONNECTED 1
#define P1_EMBED_WEBRTC_MQTT_HOST "public.cloud.shiftr.io"
#define P1_EMBED_WEBRTC_MQTT_PORT 1883
#define P1_EMBED_WEBRTC_MQTT_USER "public"
#define P1_EMBED_WEBRTC_MQTT_PASS "public"
#define P1_EMBED_WEBRTC_MQTT_ROOT XOBIT_WEBRTC_MQTT_ROOT
#define P1_EMBED_WEBRTC_MQTT_BUFFER_BYTES 8192
#define P1_EMBED_FASTLED_MAX_LEDS 5000
#define P1_EMBED_MAX_LED_STRIPS 4
#define P1_EMBED_UART_READ_STRING_MAX 256
#define P1_EMBED_HTTP_MAX_RESPONSE_BYTES 4096
#define P1_EMBED_HTTP_DEFAULT_TIMEOUT_MS 5000
#ifndef P1_EMBED_HTTP_TLS_INSECURE_DEFAULT
#define P1_EMBED_HTTP_TLS_INSECURE_DEFAULT 1
#endif
#ifndef P1_EMBED_HTTP_FAILURES_ARE_SCRIPT_ERRORS
#define P1_EMBED_HTTP_FAILURES_ARE_SCRIPT_ERRORS 0
#endif
#define P1_EMBED_JSON_ARG_MAX_BYTES 4096
#define P1_EMBED_JSON_PATH_MAX_PARTS 8
#ifndef P1_EMBED_OTA_SAFEBOOT_ENABLED
#define P1_EMBED_OTA_SAFEBOOT_ENABLED 0
#endif
#define P1_EMBED_OTA_SAFEBOOT_PARTITION_LABEL "updater"
#define P1_EMBED_OTA_REQUEST_NVS_NS "p1ota"
#define P1_EMBED_OTA_REQUEST_MAX_URL 512
#define P1_EMBED_OTA_REQUEST_MAX_SHA256 64
#define P1_EMBED_OTA_RESTART_DELAY_MS 750
#define P1_EMBED_OTA_DOWNLOAD_WIFI_WAIT_MS 45000
#ifndef P1_EMBED_OTA_ALLOW_HTTP_URLS
#define P1_EMBED_OTA_ALLOW_HTTP_URLS 0
#endif
#define P1_EMBED_HA_ENABLED 1
#define P1_EMBED_HA_PORT 6053
#define P1_EMBED_HA_ENTITY_MAX 16
#define P1_EMBED_HA_EVENT_DEPTH 8
#define P1_EMBED_HA_ID_MAX 32
#define P1_EMBED_HA_TYPE_MAX 16
#define P1_EMBED_HA_NAME_MAX 48
#define P1_EMBED_HA_UNIT_MAX 16
#define P1_EMBED_HA_RX_MAX 768
#define P1_EMBED_HA_TX_MAX 768
#define P1_EMBED_HA_API_VERSION_MAJOR 1
#define P1_EMBED_HA_API_VERSION_MINOR 14

#define P1_EMBED_SCRIPT_RUN_NONE 0
#define P1_EMBED_SCRIPT_RUN_PENDING_NEW 1
#define P1_EMBED_SCRIPT_RUN_PENDING_TRIED 2
#define P1_EMBED_SCRIPT_RUN_OK 3
#define P1_EMBED_SCRIPT_RUN_STOPPED 4

static const char* P1_EMBED_CAPABILITIES[] = {
  "transport.serial.jsonl",
#if P1_EMBED_WS_ENABLED
  "transport.websocket.json",
  "discovery.mdns",
#endif
#if P1_EMBED_WEBRTC_ENABLED
  "transport.webrtc.msgpack",
  "protocol.msgpack.v0_2",
#if P1_EMBED_WEBRTC_SIGNALING_PEERJS
  "transport.webrtc.signaling.peerjs",
#endif
#if P1_EMBED_WEBRTC_SIGNALING_MQTT
  "transport.webrtc.signaling.mqtt",
#endif
#endif
#if P1_EMBED_MQTT_ENABLED
  "transport.mqtt.msgpack",
  "protocol.msgpack.v0_2",
#endif
  "protocol.v0_1",
  "memory.profile",
#if P1_EMBED_WRENCH_ENABLED
  "wrench.compile",
  "wrench.setup_loop",
  "wrench.task",
  "wrench.time_slices",
  "wrench.runtime_mutex",
  "wrench.watchdog.status",
  "debug.event_bus",
  "debug.level_filter",
  "wrench.bindings.core",
  "config.fs.json",
  "config.identity.mac",
  "wifi.station",
  "wifi.station.fallbacks",
  "script.storage.littlefs",
  "script.autorun.safe_latch",
  "wrench.bindings.protocol_services",
  "wrench.bindings.http_fetch",
  "wrench.bindings.json_helpers",
  "wrench.bindings.ui_guino",
  "wrench.inbox.protocol_input",
  "wrench.bindings.esp_basic",
  "wrench.bindings.i2c_basic",
  "wrench.bindings.secondary_uart",
  "wrench.bindings.pwm_servo_fan",
  "wrench.bindings.led_ws2812b",
  "wrench.bindings.led_hsv",
#if P1_EMBED_HA_ENABLED
  "transport.esphome.native_api.experimental",
  "wrench.bindings.home_assistant",
#endif
#endif
#if P1_EMBED_OTA_SAFEBOOT_ENABLED
  "firmware.update.safeboot.experimental",
#endif
  "led.manager.multistrip",
  "script.error.last"
};

static const int P1_EMBED_CAPABILITY_COUNT =
  sizeof(P1_EMBED_CAPABILITIES) / sizeof(P1_EMBED_CAPABILITIES[0]);
